// Generate an HTML-based background check report and store in 'reports' bucket.
// (HTML is returned & also stored; a real PDF can be produced client-side via flutter `printing`.)
import { handleCors, corsHeaders } from '../_shared/cors.ts';
import { getServiceClient, getUser } from '../_shared/supabase.ts';

function esc(s: unknown) { return String(s ?? '').replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]!)); }

Deno.serve(async (req) => {
  const cors = handleCors(req); if (cors) return cors;
  try {
    await getUser(req);
    const { background_check_id } = await req.json();
    const sb = getServiceClient();

    const { data: bg } = await sb.from('background_checks').select('*').eq('id', background_check_id).single();
    if (!bg) throw new Error('not found');
    const { data: cand } = await sb.from('candidates').select('*').eq('id', bg.candidate_id).single();
    const { data: prof } = await sb.from('profiles').select('*').eq('id', cand!.profile_id).single();
    const { data: emp } = await sb.from('employment_history').select('*').eq('candidate_id', cand!.id).order('start_date',{ascending:false});
    const { data: edu } = await sb.from('education').select('*').eq('candidate_id', cand!.id);
    const { data: refs } = await sb.from('references').select('*').eq('background_check_id', bg.id);
    const { data: crims } = await sb.from('criminal_records').select('*').eq('background_check_id', bg.id);

    const html = `<!doctype html><html><head><meta charset="utf-8"><title>BG Check Report</title>
<style>
body{font-family:-apple-system,Roboto,Arial,sans-serif;color:#1a1a1a;margin:40px;max-width:800px}
h1{color:#0a4d68;border-bottom:3px solid #088395;padding-bottom:8px}
h2{color:#088395;margin-top:30px;border-left:4px solid #05bfdb;padding-left:10px}
table{width:100%;border-collapse:collapse;margin:10px 0}
th,td{text-align:left;padding:8px;border-bottom:1px solid #e5e7eb;font-size:14px}
th{background:#f0fafd}
.badge{display:inline-block;padding:4px 10px;border-radius:12px;font-weight:600;font-size:12px}
.b-low{background:#dcfce7;color:#166534}
.b-med{background:#fef9c3;color:#854d0e}
.b-high{background:#fee2e2;color:#991b1b}
.b-crit{background:#1f2937;color:#fff}
.meta{color:#6b7280;font-size:12px}
.footer{margin-top:60px;border-top:1px solid #e5e7eb;padding-top:10px;color:#6b7280;font-size:11px}
</style></head><body>
<h1>Background Check Report</h1>
<p class="meta">Report ID: ${esc(bg.id)} · Generated: ${new Date().toISOString()}</p>

<h2>Candidate</h2>
<table>
<tr><th>Full name</th><td>${esc(prof?.full_name)}</td></tr>
<tr><th>Fayda FCN</th><td>${esc(prof?.fayda_fcn ?? 'not provided')} <span class="badge b-${prof?.fayda_verification_status==='verified'?'low':'high'}">${esc(prof?.fayda_verification_status)}</span></td></tr>
<tr><th>Date of birth</th><td>${esc(prof?.date_of_birth)}</td></tr>
<tr><th>Phone</th><td>${esc(prof?.phone)}</td></tr>
<tr><th>Current position</th><td>${esc(cand?.current_position)}</td></tr>
<tr><th>Years of experience</th><td>${esc(cand?.years_experience)}</td></tr>
</table>

<h2>Risk Assessment</h2>
<p>Score: <strong>${esc(bg.risk_score)}/100</strong>
<span class="badge b-${bg.risk_level==='low'?'low':bg.risk_level==='medium'?'med':bg.risk_level==='high'?'high':'crit'}">${esc(bg.risk_level)}</span></p>
<table><tr><th>Factor</th><th>Weight</th><th>Description</th></tr>
${(bg.risk_factors??[]).map((f:any)=>`<tr><td>${esc(f.code)}</td><td>${esc(f.weight)}</td><td>${esc(f.description)}</td></tr>`).join('')}
</table>

<h2>Employment History (${emp?.length ?? 0})</h2>
<table><tr><th>Employer</th><th>Position</th><th>Period</th><th>Verified</th></tr>
${(emp??[]).map(e=>`<tr><td>${esc(e.employer_name)}</td><td>${esc(e.position_title)}</td><td>${esc(e.start_date)} → ${esc(e.end_date ?? 'present')}</td><td>${e.verified?'✓':'—'}</td></tr>`).join('')}
</table>

<h2>Education (${edu?.length ?? 0})</h2>
<table><tr><th>Institution</th><th>Degree</th><th>Field</th><th>End</th></tr>
${(edu??[]).map(e=>`<tr><td>${esc(e.institution_name)}</td><td>${esc(e.degree)}</td><td>${esc(e.field_of_study)}</td><td>${esc(e.end_date)}</td></tr>`).join('')}
</table>

<h2>References (${refs?.length ?? 0})</h2>
<table><tr><th>Referee</th><th>Relationship</th><th>Responded</th><th>Rating</th><th>Rehire?</th></tr>
${(refs??[]).map(r=>`<tr><td>${esc(r.referee_name)}</td><td>${esc(r.relationship)}</td><td>${r.response_received?'✓':'—'}</td><td>${esc(r.rating ?? '-')}</td><td>${r.would_rehire===null?'-':(r.would_rehire?'Yes':'No')}</td></tr>`).join('')}
</table>

<h2>Criminal Records</h2>
<table><tr><th>Jurisdiction</th><th>Records?</th><th>Status</th></tr>
${(crims??[]).map(c=>`<tr><td>${esc(c.jurisdiction)}</td><td>${c.has_records?'Yes':'No'}</td><td>${esc(c.status)}</td></tr>`).join('')}
</table>

<div class="footer">Confidential — generated by Fayda BG-Check. Distribution to unauthorized parties is prohibited.</div>
</body></html>`;

    const path = `${prof!.id}/${bg.id}.html`;
    const { error: upErr } = await sb.storage.from('reports').upload(path, new Blob([html], { type: 'text/html' }), { upsert: true, contentType: 'text/html' });
    if (upErr) throw upErr;

    const { data: signed } = await sb.storage.from('reports').createSignedUrl(path, 60 * 60 * 24 * 7);

    await sb.from('background_checks').update({
      report_url: signed?.signedUrl,
      completed_at: new Date().toISOString(),
      status: 'completed',
    }).eq('id', bg.id);

    return new Response(JSON.stringify({ ok: true, report_url: signed?.signedUrl, html_preview: html.slice(0, 200) }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (e) {
    return new Response(JSON.stringify({ error: String(e) }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
